### ISSUE TITLE
Frame rate 

### ISSUE THREAD

**Issue by LGEx** [kinectron/kinectron#26]
Hello lisa,
First of all congratulations for your work, it's really interesting.

Could you please tell me how to control the frames per second during the acquisition of body tracking and Color? Can you select a constant frame rate (assuming the computer is good enough)?

It is my interest to compare Color and body tracking acquired with the kinect with a video of a RGB camera and the position of the body found through video processing, following the position of physical markers placed on the joints.

To make such a comparison, I would need both videos to have the same frame rate.

Waiting for your comments.

Regards

Leandro

**Comment by lisajamhoury** [comment]
Glad that you are finding the project interesting to work with! 

It's in my pipeline, but I have not yet created functionality to set the frame rate. I'm not sure that I'll be able to get to it before the end of the summer. But in your circumstance, there is an easy hack that might help you. 

In the Kinectron server folder that you downloaded on your PC, go to the file /resources/app/kinectron-app.js

In the file I've already written code to limit the frame rate on sending data from [MultiFrame](https://kinectron.github.io/docs/server2.html#multiframe), which is what you'll need to run both body and rgb at the same time. 

Go to [line 1152](https://github.com/kinectron/kinectron/blob/bad801151236a21d5b6b2e2c8ebe6cb9b8e8d5c3/app/kinectron-app.js#L1152) and comment in lines 1152 - 1155 and comment out line 1158, so it should look like this. 

`     //Frame rate limiting
       if (Date.now() > sentTime + 40) {
         sendToPeer('multiFrame', multiToSend);
         sentTime = Date.now();
       }
      
      // No Framerate limiting
      // sendToPeer('multiFrame', multiToSend);`  

If you save the file and refresh or reopen the server, this frame rate limiting will now be in effect. 

Since this is limiting only the sending of data, I think you'll need to [record](https://kinectron.github.io/docs/api2.html#recording) your data from the client side. There's currently a bug in the client-side record for video, but I'll be pushing a fix to it later today. I'd recommend running the client on the same computer that your server is on to limit any delay over your network.  

Hope this helps!
