### ISSUE TITLE
personal peer network

### ISSUE THREAD

**Issue by profjere** [kinectron/kinectron#40]
This may have been asked already--I'm a bit unclear on how to set up a personal peer network if you want to connect a second computer that is not on the same wireless network.  I imagine the computer that has the Kinect connected to it has to be running off a server hosted on the same computer?  I think I'm not even sure where to start thinking about this.

**Comment by lisajamhoury** [comment]
If you want your server to be publicly available you have to put the server on the web. Kinectron uses [PeerJS](https://peerjs.com/ ) for its server. So you would need to create a publicly available PeerJS server.

Here are their instructions for the peerjs server: https://github.com/peers/peerjs-server

According to the PeerJS website they host a free cloud server (Go to the homepage and scroll to "If you don't want to run your own PeerServer, we offer a free cloud-hosted version of PeerServer. Official PeerServer!") but it appears to be a broken link. It looks like there is now someone actively maintaining the library. It might be helpful to reach out to them to see if the free cloud-hosted version is still available. 

Once you have the server running, the instructions for adding it to Kinectron Server are #3 [in the documentation here](https://kinectron.github.io/docs/server3.html#peer-server) and for #3 in the [documentation here](https://kinectron.github.io/docs/api2.html#create-an-instance-of-kinectron) for the Kinectron Client. 

I'm closing this issue because writing a tutorial about this is already assigned to @montoyamoraga [here](https://github.com/kinectron/kinectron-tutorials/issues/1). @profjere Please feel free to comment on that thread if you have additional questions or successes!
